### ISSUE TITLE
Tips for IP not getting banned by google

### ISSUE THREAD

**Issue by gajewsk2** [hellock/icrawler#27]
Just curious on if people have their IP blacklisted by google by using this and tips to avoid it, eg max number of requests in X amount of time? What measures does the crawler already take in this regard?

**Comment by hellock** [comment]
Currently there is not any limitation for request frequency since getting banned by Google is not common if you are not very aggressive. You can hack the feeder or parser to add some delay between two requests.

Some measures for this issue.
- **Fake header**. Requests sent by icrawler come with a fake header, pretending to be a web browser. (by default)
- **Proxy**. If the anti-crawler strategy is very strict, you can use proxies. See ![the documentation](http://icrawler.readthedocs.io/en/latest/proxy.html) for more details.

**Comment by gajewsk2** [comment]
That link to proxy documentation seems to be corrupted

**Comment by hellock** [comment]
Fixed.
