### ISSUE TITLE
Dose the crawler support multiple key words? 

### ISSUE THREAD

**Issue by ywang370** [hellock/icrawler#43]
It seems that the crawled images are limited per website per keyword.  I manually checked the webpage and it seems that the displayed images are limited.

**Comment by hellock** [comment]
I guess that you refer to `GoogleImageCrawler`.

1. You can crawl multiple keywords following [this answer](https://stackoverflow.com/questions/44292193/how-to-crawl-multiple-keywords-with-python-icrawler/44997471#44997471).

2. The number limit for google image search is 1000, even if you use a browser. This limitation is due to google's policy. A walk around is to define date ranges like the following.
```python
crawler.crawl('bird', max_num=1000, date_min=date(2015, 1, 1), date_max=date(2015, 12, 31))
crawler.crawl('bird', max_num=1000, date_min=date(2016,1,1), date_max=date(2016, 12, 31), file_idx_offset='auto')
crawler.crawl('bird', max_num=1000, date_min=date(2017,1,1), date_max=date(2017, 12, 31), file_idx_offset='auto')
```
