### ISSUE TITLE
Can we use the order information of the SE as the name of results?

### ISSUE THREAD

**Issue by yuchenlin** [hellock/icrawler#9]
I found that the filename order of my result pics for a single query is not the order of the SE result.

**Comment by hellock** [comment]
This can be done by overwriting the `Parser.parse` (put the order as meta data into `img_task`) and `Downloader.set_file_path` (get image name from meta data and set the filename) methods, but there are some restrictions.
- If you want to keep the order, the parser thread num should be set to 1, otherwise the multiple thread pipeline will cause problems with image filenames.
- Some images many be broken or cannot be downloaded, so the filename is not continuous
